apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: {{ .Values.natsStreaming.storageSize }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.natsStreaming.pv.serverUrl }}
    path: /