kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.natsStreaming.pv.volumeName }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.natsStreaming.storageSize }}